### ISSUE TITLE
How to specify the Element image

### ISSUE THREAD

**Issue by pmsteil** [bigwilliam/cornerstone-library-template#1]
Hey William, I created my first Element plugin based on your code, THANKS!  Was pretty easy!

One question, how do you specify your own icon for the element in the elements tab (see screenshot):
http://screencast.com/t/rqlcSPGOb

Thanks!

**Comment by cobbman** [comment]
Hi Patrick,
I need to update this code actually! It's still the legacy version which doesn't
support icons. I'll be pushing up the new version very soon.
A lot has changed with the new version, and I'm working on a video tutorial for
how to make them. I'll be posting that on cornerstonelibrary.com when it is
ready.

**Comment by cobbman** [comment]
Hi Patrick,

I've pushed the new version up, and tagged it v2.4. Sorry if you already went through so much work to make the first one. I'm going to get this updated on CornerstoneLibrary.com as well.

Also, you will notice in the file [my-extension.php](https://github.com/bigwilliam/cornerstone-library-template/blob/master/my-extension.php) that there is a function to set the icon (svg).

**Comment by pmsteil** [comment]
Ah ok, thanks so much!
